server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    max-http-form-post-size: 10485760
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: test
    password:
#  sql:
#    init:
#      data-locations:
#        - classpath:db/data.sql
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    #      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

